version: "3.8"

services:
  proxy:
    image: caddy:2
    container_name: timetracker-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ACME_EMAIL=${ACME_EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - timetracker-net

  backend:
    image: ghcr.io/kirillgolunov/actionkeeper-backend:latest
    container_name: timetracker-backend
    env_file:
      - .env
    expose:
      - "3001"
    volumes:
      - ./data:/app/data
      - ./smtp_settings.json:/app/smtp_settings.json:ro
    restart: unless-stopped
    networks:
      - timetracker-net

  frontend:
    image: ghcr.io/kirillgolunov/actionkeeper-frontend:latest
    container_name: timetracker-frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - timetracker-net

networks:
  timetracker-net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
